name: Vale Linting
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  vale-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Vale Linter
        uses: errata-ai/vale-action@reviewdog
        env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: docs/
